const SECRETS = [
{id:1,category:"generic",title:"Multiply Anything by 11 in Your Head",keywords:["multiply","11","fast"],
simple:"This makes people think you have a calculator in your brain.",
how:"Add the two digits together and put the answer in the middle. If it’s more than 9, carry the 1.",
examples:[{q:"23 times 11",a:"2 plus 3 is 5. Answer is 253"},{q:"47 times 11",a:"4 plus 7 is 11. Put 1 carry 1. Answer is 517"},{q:"68 times 11",a:"6 plus 8 is 14. Put 4 carry 1. Answer is 748"},{q:"99 times 11",a:"9 plus 9 is 18. Put 8 carry 1. Answer is 1089"},{q:"123 times 11",a:"Do 1, then 1 plus 2, then 2 plus 3, then 3. Answer is 1353"}],
examTip:"Works for any size number. Just keep adding neighbors."},

{id:2,category:"generic",title:"Square Any Number Ending in 5",keywords:["square","5"],
simple:"You can square 35, 85, 125 in 2 seconds.",
how:"Take the number before the 5. Multiply it by the next number. Then put 25 at the end.",
examples:[{q:"25 squared",a:"2 times 3 is 6. Add 25. Answer is 625"},{q:"35 squared",a:"3 times 4 is 12. Add 25. Answer is 1225"},{q:"65 squared",a:"6 times 7 is 42. Add 25. Answer is 4225"},{q:"85 squared",a:"8 times 9 is 72. Add 25. Answer is 7225"},{q:"105 squared",a:"10 times 11 is 110. Add 25. Answer is 11025"}],
examTip:"This works because 5 squared is always 25."},

{id:3,category:"generic",title:"Multiply by 9 Using Your Fingers",keywords:["multiply","9"],
simple:"Forgot your times table. Use your hands.",
how:"Hold up 10 fingers. To do 9 times 4, put down the 4th finger. Count fingers left and right.",
examples:[{q:"9 times 3",a:"Put down 3rd finger. 2 on left, 7 on right. Answer is 27"},{q:"9 times 6",a:"Put down 6th finger. 5 on left, 4 on right. Answer is 54"},{q:"9 times 8",a:"Put down 8th finger. 7 on left, 2 on right. Answer is 72"},{q:"9 times 1",a:"Put down 1st finger. 0 on left, 9 on right. Answer is 09"},{q:"9 times 10",a:"Put down 10th finger. 9 on left, 0 on right. Answer is 90"}],
examTip:"Kids learn this in 1 minute and never forget 9 times table."},

{id:4,category:"generic",title:"Find Any Percentage Without Calculator",keywords:["percentage","percent"],
simple:"Flip the numbers. X percent of Y is the same as Y percent of X.",
how:"Instead of doing 16 percent of 25, do 25 percent of 16. Way easier.",
examples:[{q:"8 percent of 50",a:"Do 50 percent of 8. Half of 8 is 4"},{q:"25 percent of 64",a:"Do 64 percent of 25. Quarter of 64 is 16"},{q:"10 percent of 300",a:"Do 300 percent of 10. 3 times 10 is 30"},{q:"12 percent of 50",a:"Do 50 percent of 12. Half of 12 is 6"},{q:"20 percent of 75",a:"Do 75 percent of 20. One fifth of 75 is 15"}],
examTip:"This saves you in shop discounts and exams."},

{id:5,category:"generic",title:"Check if a Number Divides by 11",keywords:["division","11"],
simple:"Fast way to know if 121 or 1331 can divide by 11.",
how:"Add digits in odd spots. Add digits in even spots. Subtract. If you get 0 or 11, it divides by 11.",
examples:[{q:"121",a:"1 plus 1 is 2. Minus 2 is 0. Yes it divides"},{q:"242",a:"2 plus 2 is 4. Minus 4 is 0. Yes it divides"},{q:"1234",a:"1 plus 3 is 4. 2 plus 4 is 6. 4 minus 6 is minus 2. No"},{q:"1331",a:"1 plus 3 is 4. 3 plus 1 is 4. 4 minus 4 is 0. Yes"},{q:"4565",a:"4 plus 6 is 10. 5 plus 5 is 10. 10 minus 10 is 0. Yes"}],
examTip:"Use this to factor numbers fast."},

{id:6,category:"generic",title:"Multiply Numbers Near 100",keywords:["multiply","100"],
simple:"For 98 times 97, you don't need to do long multiplication.",
how:"Find how far each number is from 100. Subtract crosswise. Multiply the differences.",
examples:[{q:"98 times 97",a:"98 is 2 less. 97 is 3 less. 98 minus 3 is 95. 2 times 3 is 06. Answer is 9506"},{q:"99 times 98",a:"99 is 1 less. 98 is 2 less. 99 minus 2 is 97. 1 times 2 is 02. Answer is 9702"},{q:"102 times 103",a:"102 is 2 more. 103 is 3 more. 102 plus 3 is 105. 2 times 3 is 06. Answer is 10506"},{q:"97 times 96",a:"97 is 3 less. 96 is 4 less. 97 minus 4 is 93. 3 times 4 is 12. Answer is 9312"},{q:"101 times 104",a:"101 is 1 more. 104 is 4 more. 101 plus 4 is 105. 1 times 4 is 04. Answer is 10504"}],
examTip:"Works for any number close to 100."},

{id:7,category:"generic",title:"Find Unit Digit of Big Powers",keywords:["unit digit","power"],
simple:"What is the last digit of 7 to the power 23. Don't multiply 23 times.",
how:"Last digits repeat in cycles of 4. Find the remainder when power is divided by 4.",
examples:[{q:"Last digit of 3 to the power 10",a:"3 cycles 3,9,7,1. 10 divided by 4 leaves 2. 2nd in cycle is 9"},{q:"Last digit of 7 to the power 23",a:"7 cycles 7,9,3,1. 23 divided by 4 leaves 3. 3rd in cycle is 3"},{q:"Last digit of 2 to the power 8",a:"2 cycles 2,4,8,6. 8 divided by 4 leaves 0. Last in cycle is 6"},{q:"Last digit of 4 to the power 100",a:"4 always ends in 4 or 6. Even power ends in 6"},{q:"Last digit of 9 to the power 15",a:"9 cycles 9,1. Odd power ends in 9"}],
examTip:"Competition exams ask this a lot."},

{id:8,category:"generic",title:"Quick Profit and Loss Trick",keywords:["profit","loss"],
simple:"If you buy and sell, how to get percent profit fast.",
how:"Profit percent equals selling price minus cost price divided by cost price times 100.",
examples:[{q:"Bought for 100, sold for 120",a:"20 divided by 100 times 100. 20 percent profit"},{q:"Bought for 200, sold for 150",a:"Minus 50 divided by 200 times 100. 25 percent loss"},{q:"Bought for 80, sold for 100",a:"20 divided by 80 times 100. 25 percent profit"},{q:"Bought for 500, sold for 625",a:"125 divided by 500 times 100. 25 percent profit"},{q:"Bought for 40, sold for 32",a:"Minus 8 divided by 40 times 100. 20 percent loss"}],
examTip:"Always divide by cost price, not selling price."},

{id:9,category:"generic",title:"Time Speed Distance Tricks",keywords:["time","speed","distance"],
simple:"3 things. If you know 2, you get the 3rd.",
how:"Distance equals speed times time. Rearrange it however you need.",
examples:[{q:"Car goes 60 km per hour for 2 hours",a:"60 times 2. Distance is 120 km"},{q:"Distance 300 km, time 5 hours",a:"300 divided by 5. Speed is 60 km per hour"},{q:"Distance 150 km, speed 50 km per hour",a:"150 divided by 50. Time is 3 hours"},{q:"Train 90 km per hour for 45 minutes",a:"45 minutes is 0.75 hours. 90 times 0.75 is 67.5 km"},{q:"Two cars 60 and 40 km per hour towards each other",a:"Add speeds. 100 km per hour together"}],
examTip:"Convert minutes to hours by dividing by 60."},

{id:10,category:"generic",title:"LCM and HCF in 10 Seconds",keywords:["lcm","hcf"],
simple:"Find biggest number that divides both. And smallest number both divide.",
how:"For HCF, find common factors. For LCM, multiply numbers then divide by HCF.",
examples:[{q:"HCF of 12 and 18",a:"Common factors. 6 is biggest. Answer is 6"},{q:"LCM of 4 and 6",a:"4 times 6 is 24. Divide by HCF 2. Answer is 12"},{q:"HCF of 20 and 25",a:"5 is common. Answer is 5"},{q:"LCM of 7 and 8",a:"No common factor. Answer is 56"},{q:"HCF of 48 and 60",a:"12 divides both. Answer is 12"}],
examTip:"LCM times HCF equals product of two numbers."},

{id:11,category:"generic",title:"Average Speed for Two Trips",keywords:["average","speed"],
simple:"If you go and come back at different speeds, average is not just add and divide by 2.",
how:"Use harmonic mean. 2 times speed1 times speed2 divided by speed1 plus speed2.",
examples:[{q:"Go 40, return 60",a:"2 times 40 times 60 divided by 100. Answer is 48"},{q:"Go 30, return 70",a:"2 times 30 times 70 divided by 100. Answer is 42"},{q:"Go 50, return 50",a:"Same speed. Answer is 50"},{q:"Go 20, return 80",a:"2 times 20 times 80 divided by 100. Answer is 32"},{q:"Go 10, return 90",a:"2 times 10 times 90 divided by 100. Answer is 18"}],
examTip:"If distances are equal, use this formula."},

{id:12,category:"generic",title:"Compound Interest Shortcut",keywords:["interest","compound"],
simple:"Money growing on money.",
how:"Amount equals principal times 1 plus rate divided by 100 to the power time.",
examples:[{q:"1000 at 10 percent for 2 years",a:"1000 times 1.1 times 1.1. Answer is 1210"},{q:"5000 at 5 percent for 3 years",a:"5000 times 1.05 cubed. About 5788"},{q:"2000 at 20 percent for 2 years",a:"2000 times 1.2 times 1.2. Answer is 2880"},{q:"10000 at 8 percent for 1 year",a:"10000 times 1.08. Answer is 10800"},{q:"500 at 12 percent for 2 years",a:"500 times 1.12 times 1.12. Answer is 627.2"}],
examTip:"For quick estimate, use rule of 72 to double money."},

{id:13,category:"generic",title:"Mixture and Alligation",keywords:["mixture","ratio"],
simple:"Mixing two things with different prices.",
how:"Draw a line. Put prices. Difference gives ratio.",
examples:[{q:"Mix 20 per kg and 30 per kg to get 25 per kg",a:"Differences 5 and 5. Ratio 1 to 1"},{q:"Mix tea 50 and 70 to get 60",a:"Differences 10 and 10. Ratio 1 to 1"},{q:"Mix milk 40 and 60 to get 50",a:"Differences 10 and 10. Ratio 1 to 1"},{q:"Mix 100 and 200 to get 160",a:"Differences 40 and 60. Ratio 2 to 3"},{q:"Mix 10 and 40 to get 25",a:"Differences 15 and 15. Ratio 1 to 1"}],
examTip:"Bigger difference means less quantity of that item."},

{id:14,category:"generic",title:"Age Problems Made Easy",keywords:["age","ratio"],
simple:"Father is 3 times son now. After 10 years he will be 2 times.",
how:"Take present ages. Add or subtract years. Make equation.",
examples:[{q:"Father 3 times son. Sum is 40",a:"4 parts is 40. Son is 10, father is 30"},{q:"After 5 years father will be 2 times son",a:"Let son be x. 3x plus 5 equals 2 times x plus 5. Solve"},{q:"Difference of ages is 20. Ratio is 3 to 1",a:"2 parts is 20. So ages are 30 and 10"},{q:"5 years ago father was 4 times son",a:"Set up equation with minus 5"},{q:"In 10 years ratio will be 2 to 1",a:"Set up equation with plus 10"}],
examTip:"Difference in ages never changes."},

{id:15,category:"generic",title:"Train Problems",keywords:["train","speed"],
simple:"Train crossing pole, bridge, or another train.",
how:"If crossing pole, use length of train. If crossing bridge, add lengths.",
examples:[{q:"Train 200 meters at 72 km per hour crosses pole",a:"72 kmph is 20 meters per second. 200 divided by 20 is 10 seconds"},{q:"Train crosses 300 meter bridge",a:"Add train length plus bridge length"},{q:"Two trains opposite direction",a:"Add speeds"},{q:"Two trains same direction",a:"Subtract speeds"},{q:"Train passes man in 10 seconds",a:"Speed equals length divided by 10"}],
examTip:"Convert kmph to mps by multiplying by 5 divided by 18."},

{id:16,category:"generic",title:"Boats and Streams",keywords:["boat","stream"],
simple:"Boat speed changes with water flow.",
how:"Downstream equals boat speed plus stream speed. Upstream equals boat minus stream.",
examples:[{q:"Boat 10, stream 2 downstream",a:"10 plus 2. Answer is 12"},{q:"Boat 10, stream 2 upstream",a:"10 minus 2. Answer is 8"},{q:"Downstream 24, upstream 16",a:"Boat speed is 24 plus 16 divided by 2. Answer is 20"},{q:"Takes 4 hours downstream, 6 upstream for same distance",a:"Set up equation"},{q:"Stream speed is half boat speed",a:"Let boat be 2x, stream be x"}],
examTip:"Boat speed is average of upstream and downstream."},

{id:17,category:"generic",title:"Work and Pipes",keywords:["work","pipes"],
simple:"A can do work in 10 days, B in 15 days. Together.",
how:"Add their 1 day work. Take reciprocal for total days.",
examples:[{q:"A in 10 days, B in 15 days together",a:"1 over 10 plus 1 over 15. Answer is 6 days"},{q:"Pipe A fills in 20 minutes, B empties in 30",a:"1 over 20 minus 1 over 30. Answer is 60 minutes"},{q:"A in 5 days, B in 10, C in 15",a:"Add all three reciprocals"},{q:"A and B together in 12 days",a:"Their combined 1 day work is 1 over 12"},{q:"A is twice as fast as B",a:"If B takes x days, A takes x over 2"}],
examTip:"Negative work means emptying."},

{id:18,category:"generic",title:"Ratio and Proportion",keywords:["ratio","proportion"],
simple:"Compare two quantities.",
how:"Write as a fraction. Cross multiply to find missing value.",
examples:[{q:"Ratio 2 to 3. Sum is 50",a:"5 parts is 50. So 20 and 30"},{q:"4 to 5 equals x to 20",a:"Cross multiply. 4 times 20 divided by 5. x is 16"},{q:"Divide 100 in ratio 3 to 2",a:"3 plus 2 is 5. 100 divided by 5 is 20. So 60 and 40"},{q:"A to B is 3 to 4, B to C is 5 to 6",a:"Make B same. Answer is 15 to 20 to 24"},{q:"Continued proportion a to b to c",a:"b squared equals a times c"}],
examTip:"In proportion, product of extremes equals product of means."},

{id:19,category:"generic",title:"Calendar and Days",keywords:["calendar","day"],
simple:"What day was Jan 1 2000.",
how:"Count odd days. Leap year adds 1 extra day.",
examples:[{q:"Odd days in 1 year",a:"365 divided by 7 leaves 1 odd day"},{q:"Odd days in leap year",a:"2 odd days"},{q:"Jan 1 2024 is Monday",a:"2025 Jan 1 will be Wednesday because 2024 is leap"},{q:"100 years has 5 odd days",a:"Used to find century day"},{q:"Find day after 50 days",a:"50 divided by 7 leaves 1. So next day"}],
examTip:"Sunday 0, Monday 1, and so on."},

{id:20,category:"generic",title:"Simple Interest vs Compound Interest",keywords:["interest","simple"],
simple:"Difference between the two.",
how:"Simple interest is flat. Compound interest grows each year.",
examples:[{q:"1000 at 10 percent for 2 years simple",a:"100 plus 100. Total 200"},{q:"1000 at 10 percent for 2 years compound",a:"100 plus 110. Total 210"},{q:"Difference after 2 years",a:"10"},{q:"Difference after 3 years",a:"About 31"},{q:"When are they equal",a:"Only for 1 year"}],
examTip:"CI minus SI for 2 years equals P times R squared divided by 100 squared."},
  
{id:21,category:"university",title:"Integration by Parts The Easy Way",keywords:["calculus","integral"],
simple:"When you have two things multiplied inside integral.",
how:"Pick u using LIATE rule. Log Inverse Algebra Trig Exponential. Differentiate u, integrate dv.",
examples:[{q:"Integral of x cos x",a:"u is x. Answer is x sin x plus cos x plus C"},{q:"Integral of x e to the x",a:"Answer is x e to the x minus e to the x plus C"},{q:"Integral of ln x",a:"Answer is x ln x minus x plus C"},{q:"Integral of x squared sin x",a:"Do it twice. Answer is minus x squared cos x plus 2x sin x plus 2 cos x plus C"},{q:"Integral of arctan x",a:"Answer is x arctan x minus half ln 1 plus x squared plus C"}],
examTip:"Don't forget plus C or you lose marks."},

{id:22,category:"university",title:"Derivatives Using Power Rule",keywords:["derivative","calculus"],
simple:"How fast something is changing.",
how:"Bring power down, reduce power by 1.",
examples:[{q:"Derivative of x squared",a:"2x"},{q:"Derivative of x cubed",a:"3x squared"},{q:"Derivative of 5x",a:"5"},{q:"Derivative of 7",a:"0"},{q:"Derivative of 1 over x",a:"Minus 1 over x squared"}],
examTip:"Derivative of constant is always zero."},

{id:23,category:"university",title:"Limits Without Panic",keywords:["limit","calculus"],
simple:"What value does the function get close to.",
how:"Plug in number. If it breaks, factor or use L hospital.",
examples:[{q:"Limit of x squared as x goes to 2",a:"Plug 2. Answer is 4"},{q:"Limit of sin x over x as x goes to 0",a:"Answer is 1"},{q:"Limit of x squared minus 4 over x minus 2",a:"Factor. Answer is 4"},{q:"Limit of 1 over x as x goes to infinity",a:"Answer is 0"},{q:"Limit of e to the x as x goes to 0",a:"Answer is 1"}],
examTip:"If you get 0 over 0, try factoring."},

{id:24,category:"university",title:"Eigenvalues of a 2 by 2 Matrix",keywords:["eigenvalue","matrix"],
simple:"Special numbers that show how matrix stretches things.",
how:"Do determinant of A minus lambda I equals 0. Solve for lambda.",
examples:[{q:"Matrix 2 1 1 2",a:"Lambda is 1 and 3"},{q:"Matrix 3 0 0 2",a:"Lambda is 3 and 2"},{q:"Matrix 0 1 minus 1 0",a:"Lambda is i and minus i"},{q:"Matrix 1 1 0 1",a:"Lambda is 1 and 1"},{q:"Matrix 4 2 2 4",a:"Lambda is 2 and 6"}],
examTip:"Sum of eigenvalues equals trace of matrix."},

{id:25,category:"university",title:"Taylor Series Approximation",keywords:["taylor","series"],
simple:"Turn any function into a polynomial.",
how:"Use function value and derivatives at one point.",
examples:[{q:"Taylor of e to the x at 0",a:"1 plus x plus x squared over 2 plus x cubed over 6"},{q:"Taylor of sin x at 0",a:"x minus x cubed over 6 plus x to the 5 over 120"},{q:"Taylor of cos x at 0",a:"1 minus x squared over 2 plus x to the 4 over 24"},{q:"Taylor of ln 1 plus x at 0",a:"x minus x squared over 2 plus x cubed over 3"},{q:"First order Taylor",a:"f of a plus f prime of a times x minus a"}],
examTip:"Used to approximate hard functions."},

{id:26,category:"university",title:"Solving First Order ODE",keywords:["ode","differential"],
simple:"Equation with derivative.",
how:"Separate variables or use integrating factor.",
examples:[{q:"dy dx equals x",a:"Integrate both sides. y is x squared over 2 plus C"},{q:"dy dx equals y",a:"Separate. Answer is y equals C e to the x"},{q:"dy dx plus 2y equals 0",a:"Answer is y equals C e to the minus 2x"},{q:"dy dx equals 2x",a:"Answer is y equals x squared plus C"},{q:"dy dx equals 3y",a:"Answer is y equals C e to the 3x"}],
examTip:"Always check by differentiating your answer."},

{id:27,category:"university",title:"Probability Basics",keywords:["probability","chance"],
simple:"How likely something happens.",
how:"Number of good outcomes divided by total outcomes.",
examples:[{q:"Chance of head in coin toss",a:"1 out of 2"},{q:"Chance of 6 on dice",a:"1 out of 6"},{q:"Chance of ace in cards",a:"4 out of 52"},{q:"Chance of even number on dice",a:"3 out of 6 equals half"},{q:"Chance of red card",a:"26 out of 52 equals half"}],
examTip:"Probability is always between 0 and 1."},

{id:28,category:"university",title:"Matrix Multiplication",keywords:["matrix","multiply"],
simple:"Row times column.",
how:"Multiply row of first by column of second and add.",
examples:[{q:"1 2 times 3 4",a:"1 times 3 plus 2 times 4 equals 11"},{q:"2 by 2 times 2 by 2",a:"Do 4 multiplications and add"},{q:"Identity matrix times anything",a:"You get the same thing back"},{q:"Zero matrix times anything",a:"You get zero"},{q:"Check dimensions first",a:"Columns of first must equal rows of second"}],
examTip:"Matrix multiplication is not commutative."},

{id:29,category:"university",title:"Vectors Dot Product",keywords:["vector","dot"],
simple:"Tells you how much two vectors point same direction.",
how:"Multiply matching parts and add.",
examples:[{q:"1 2 dot 3 4",a:"1 times 3 plus 2 times 4 equals 11"},{q:"1 0 dot 0 1",a:"0. They are perpendicular"},{q:"2 2 dot 2 2",a:"8"},{q:"Dot product with itself",a:"Gives length squared"},{q:"If dot product is 0",a:"Vectors are perpendicular"}],
examTip:"Used in physics for work."},

{id:30,category:"university",title:"Complex Numbers",keywords:["complex","i"],
simple:"Numbers with square root of minus 1.",
how:"i squared equals minus 1. Add real with real, imaginary with imaginary.",
examples:[{q:"3 plus 4i plus 1 plus 2i",a:"4 plus 6i"},{q:"i times i",a:"Minus 1"},{q:"2 plus 3i times 1 plus i",a:"2 plus 2i plus 3i minus 3. Answer is minus 1 plus 5i"},{q:"Magnitude of 3 plus 4i",a:"5"},{q:"Conjugate of 2 minus 3i",a:"2 plus 3i"}],
examTip:"Used in electrical engineering."},

{id:31,category:"university",title:"Divergence of a Vector Field",keywords:["divergence","vector"],
simple:"Tells if field is spreading out or coming in.",
how:"Add partial derivatives of each component.",
examples:[{q:"Field x y z",a:"1 plus 1 plus 1 equals 3"},{q:"Field x squared y z",a:"2x plus 0 plus 0"},{q:"Field 0 0 z",a:"1"},{q:"Field x y 0",a:"2"},{q:"If divergence is 0",a:"Field is incompressible"}],
examTip:"Used in fluid dynamics."},

{id:32,category:"university",title:"Curl of a Vector Field",keywords:["curl","rotation"],
simple:"Tells if field is spinning.",
how:"Cross product of del operator and field.",
examples:[{q:"Field minus y x 0",a:"Curl points in z direction"},{q:"Field x y z",a:"Curl is 0"},{q:"If curl is 0",a:"Field is conservative"},{q:"Curl of gradient",a:"Always 0"},{q:"Curl measures rotation",a:"Like whirlpool"}],
examTip:"Right hand rule for direction."},

{id:33,category:"university",title:"Multiple Integrals",keywords:["integral","double"],
simple:"Integral over an area or volume.",
how:"Do one integral at a time.",
examples:[{q:"Integral x from 0 to 1 and 0 to 2",a:"Integrate x dx then dy. Answer is 2"},{q:"Area under curve",a:"Single integral"},{q:"Volume under surface",a:"Double integral"},{q:"Change order of integration",a:"Sometimes makes it easier"},{q:"Polar coordinates",a:"Use r dr d theta"}],
examTip:"Draw region first."},

{id:34,category:"university",title:"Bayes Theorem",keywords:["bayes","probability"],
simple:"Update belief when you get new info.",
how:"New probability equals old times likelihood divided by total.",
examples:[{q:"Disease test 99 percent accurate",a:"Use Bayes to find real chance"},{q:"Spam filter",a:"Updates based on words"},{q:"Medical diagnosis",a:"Updates after test"},{q:"Weather forecast",a:"Updates with new data"},{q:"Coin bias",a:"Updates after flips"}],
examTip:"Prior times likelihood over evidence."},

{id:35,category:"university",title:"Hypothesis Testing",keywords:["statistics","hypothesis"],
simple:"Check if claim is true using data.",
how:"Assume null is true. See how weird data is.",
examples:[{q:"Coin fair test",a:"Flip 100 times. Check if about 50 heads"},{q:"New drug works",a:"Compare to placebo"},{q:"Mean test",a:"Use z test or t test"},{q:"P value small",a:"Reject null"},{q:"95 percent confidence",a:"Means 5 percent chance of error"}],
examTip:"P value less than 0.05 means significant."},

{id:36,category:"university",title:"Chain Rule for Derivatives",keywords:["chain","derivative"],
simple:"Derivative of a function inside another function.",
how:"Derivative of outside times derivative of inside.",
examples:[{q:"Derivative of sin x squared",a:"cos x squared times 2x"},{q:"Derivative of e to the 3x",a:"3 e to the 3x"},{q:"Derivative of ln x squared",a:"2x over x squared"},{q:"Derivative of square root of x",a:"1 over 2 square root of x"},{q:"Derivative of tan 2x",a:"2 sec squared 2x"}],
examTip:"Peel it like an onion. Outside first."},

{id:37,category:"university",title:"Partial Derivatives",keywords:["partial","derivative"],
simple:"Derivative when you have more than 1 variable.",
how:"Treat other variables as constants.",
examples:[{q:"Derivative of x squared y with respect to x",a:"2x y"},{q:"Derivative of x squared y with respect to y",a:"x squared"},{q:"Derivative of sin xy",a:"y cos xy"},{q:"Second partial",a:"Do it twice"},{q:"Mixed partial",a:"Order does not matter"}],
examTip:"Used in economics and physics."},

{id:38,category:"university",title:"Improper Integrals",keywords:["integral","improper"],
simple:"Integral to infinity.",
how:"Turn infinity into a limit.",
examples:[{q:"Integral 1 over x squared from 1 to infinity",a:"Answer is 1"},{q:"Integral e to the minus x from 0 to infinity",a:"Answer is 1"},{q:"Integral 1 over x from 1 to infinity",a:"Diverges"},{q:"Gaussian integral",a:"Square root of pi"},{q:"Test for convergence",a:"Compare test"}],
examTip:"If area is finite, it converges."},

{id:39,category:"university",title:"Series Convergence Tests",keywords:["series","convergence"],
simple:"Does the sum go to a number or blow up.",
how:"Use ratio test, root test, comparison test.",
examples:[{q:"1 over n squared",a:"Converges"},{q:"1 over n",a:"Diverges"},{q:"n factorial over n to the n",a:"Converges"},{q:"Geometric series",a:"Converges if r less than 1"},{q:"Alternating series",a:"Converges if terms go to 0"}],
examTip:"Ratio test is the fastest."},

{id:40,category:"university",title:"Fourier Series Idea",keywords:["fourier","series"],
simple:"Any repeating wave equals sum of sines and cosines.",
how:"Find average, then cosine terms, then sine terms.",
examples:[{q:"Square wave",a:"Only odd sine terms"},{q:"Triangle wave",a:"Only odd cosine terms"},{q:"DC signal",a:"Just average"},{q:"Sound wave",a:"Sum of frequencies"},{q:"Image compression",a:"Uses 2D Fourier"}],
examTip:"Used in signal processing."},

  {id:41,category:"engineering",title:"Laplace Transform Without Headache",keywords:["laplace","ode","control"],
simple:"Turns calculus into algebra. Solve, then turn back.",
how:"Take Laplace of both sides. Derivatives become s times F of s minus starting value. Solve for F of s. Then flip back.",
examples:[{q:"y prime plus 3y equals 0, y at 0 is 1",a:"Turns to sY minus 1 plus 3Y equals 0. Y is 1 over s plus 3. Flip back. Answer is e to the minus 3t"},{q:"y double prime equals 0",a:"Turns to s squared Y minus sy0 minus y0 prime equals 0. Answer is y0 plus y0 prime times t"},{q:"y prime minus y equals e to the 2t",a:"Turns to sY minus 1 minus Y equals 1 over s minus 2. Answer is e to the 2t minus e to the t"},{q:"y double prime plus y equals sin t",a:"Turns to s squared Y plus Y equals 1 over s squared plus 1. Answer is half sin t minus half t cos t"},{q:"y prime plus 2y equals 5",a:"Turns to sY plus 2Y equals 5 over s. Answer is 2.5 minus 2.5 e to the minus 2t"}],
examTip:"Memorize these 3. 1 becomes 1 over s. e to the at becomes 1 over s minus a. sin wt becomes w over s squared plus w squared"},

{id:42,category:"engineering",title:"Inverse Laplace From Tables",keywords:["laplace","inverse"],
simple:"You got F of s. Now turn it back to time.",
how:"Break it into pieces you know. Use partial fractions if needed.",
examples:[{q:"1 over s plus 3",a:"Flip back. Answer is e to the minus 3t"},{q:"1 over s squared",a:"Flip back. Answer is t"},{q:"w over s squared plus w squared",a:"Flip back. Answer is sin wt"},{q:"s over s squared plus w squared",a:"Flip back. Answer is cos wt"},{q:"1 over s times s plus a",a:"Do partial fractions. Answer is 1 over a times 1 minus e to the minus at"}],
examTip:"Keep a Laplace table next to you in exam. 90 percent of questions come from it"},

{id:43,category:"engineering",title:"Fourier Series Any Signal as Sines",keywords:["fourier","signal"],
simple:"Any repeating wave can be built with sin and cos blocks.",
how:"Find a0 for average. Find an for cos terms. Find bn for sin terms.",
examples:[{q:"Square wave",a:"Only odd sine terms. 4 over pi times sin wt plus 1 over 3 sin 3wt plus..."},{q:"Triangle wave",a:"Only odd cosine terms with 1 over n squared"},{q:"DC signal",a:"Only a0. No sin or cos"},{q:"Sawtooth wave",a:"Both sin terms with 1 over n"},{q:"Even function",a:"Only cos terms. No sin"}],
examTip:"Even function no sin. Odd function no cos. Saves half the work"},

{id:44,category:"engineering",title:"Z Transform for Digital Signals",keywords:["z transform","digital"],
simple:"Laplace for discrete time. Used in DSP.",
how:"Turn sequence into function of z. Delay becomes z to the minus 1.",
examples:[{q:"Unit impulse",a:"Z transform is 1"},{q:"Unit step",a:"Z transform is 1 over 1 minus z to the minus 1"},{q:"a to the n",a:"Z transform is 1 over 1 minus a z to the minus 1"},{q:"Delay by 1",a:"Multiply by z to the minus 1"},{q:"Difference equation",a:"Turn to algebra in z domain"}],
examTip:"Final value theorem. Limit as z goes to 1 of 1 minus z to the minus 1 times F of z"},

{id:45,category:"engineering",title:"State Space Model",keywords:["state","control"],
simple:"Write system with first order equations using state variables.",
how:"Pick states. Write x dot equals Ax plus Bu. y equals Cx plus Du.",
examples:[{q:"Mass spring damper",a:"States are position and velocity"},{q:"RLC circuit",a:"States are capacitor voltage and inductor current"},{q:"DC motor",a:"States are speed and current"},{q:"Check controllability",a:"Rank of controllability matrix"},{q:"Check observability",a:"Rank of observability matrix"}],
examTip:"State space is better than transfer function for multi input multi output"},

{id:46,category:"engineering",title:"Routh Hurwitz Stability Test",keywords:["routh","stability"],
simple:"Check if system is stable without solving roots.",
how:"Make Routh table. If any number in first column is negative, unstable.",
examples:[{q:"s cubed plus 2s squared plus 3s plus 4",a:"First column all positive. Stable"},{q:"s cubed minus s squared plus 2s plus 8",a:"First column has negative. Unstable"},{q:"Find range of K for stability",a:"Set first column greater than 0"},{q:"Row of zeros",a:"Means symmetric roots"},{q:"Marginally stable",a:"Row of zeros with no sign change"}],
examTip:"Number of sign changes equals number of right half plane poles"},

{id:47,category:"engineering",title:"Bode Plot Basics",keywords:["bode","frequency"],
simple:"Graph of gain and phase vs frequency.",
how:"Break transfer function into factors. Add gains in dB. Add phases.",
examples:[{q:"1 over s",a:"Slope minus 20 dB per decade. Phase minus 90"},{q:"1 over s plus 1",a:"Corner at 1 rad per sec"},{q:"s plus 1",a:"Slope plus 20 dB per decade. Phase plus 90"},{q:"Second order",a:"Peak near natural frequency"},{q:"Gain margin",a:"How much gain before unstable"}],
examTip:"Gain crossover is where magnitude is 0 dB"},

{id:48,category:"engineering",title:"Nyquist Stability Criterion",keywords:["nyquist","stability"],
simple:"Plot transfer function in complex plane to check stability.",
how:"Plot G of jw. Count encirclements of minus 1 point.",
examples:[{q:"Stable open loop",a:"No encirclement of minus 1"},{q:"Unstable open loop",a:"Encirclements matter"},{q:"Gain margin",a:"Distance to minus 1 on real axis"},{q:"Phase margin",a:"Angle to minus 1 at gain crossover"},{q:"Closed loop stable",a:"N equals Z minus P"}],
examTip:"N is encirclements. Z is unstable closed loop poles. P is unstable open loop poles"},

{id:49,category:"engineering",title:"Numerical Integration Trapezoid Rule",keywords:["numerical","integration"],
simple:"Approximate area under curve with trapezoids.",
how:"Add first and last. Add middle times 2. Multiply by width over 2.",
examples:[{q:"Integral x squared from 0 to 2 with 2 strips",a:"Width is 1. Answer is 1 over 2 times 0 plus 8 plus 2 times 1. Answer is 2.666"},{q:"More strips means better accuracy",a:"Error goes down"},{q:"Simpson rule is better",a:"Uses parabolas"},{q:"Used in FEM",a:"Finite element method"},{q:"Error estimate",a:"Proportional to width squared"}],
examTip:"Trapezoid is average of left and right Riemann sum"},

{id:50,category:"engineering",title:"Newton Raphson Root Finding",keywords:["newton","root"],
simple:"Find where function equals 0 fast.",
how:"Start with guess. Draw tangent. Where tangent hits x axis is next guess.",
examples:[{q:"x squared minus 2 equals 0",a:"Start at 1. Next guess is 1.5. Then 1.414"},{q:"cos x minus x equals 0",a:"Converges to 0.739"},{q:"Needs derivative",a:"Formula is x new equals x minus f over f prime"},{q:"May diverge",a:"If starting guess is bad"},{q:"Quadratic convergence",a:"Doubles correct digits each step"}],
examTip:"Used in power flow and nonlinear circuits"},

{id:51,category:"engineering",title:"Euler Method for ODE",keywords:["euler","ode"],
simple:"Solve differential equation step by step.",
how:"y new equals y old plus step size times derivative.",
examples:[{q:"y prime equals y, y0 equals 1, step 0.1",a:"y1 equals 1 plus 0.1 times 1. Answer is 1.1"},{q:"Small step better accuracy",a:"But more computation"},{q:"Error is first order",a:"Proportional to step size"},{q:"Used for real time",a:"Simple to code"},{q:"Improved Euler",a:"Predictor corrector"}],
examTip:"Not accurate for stiff equations"},

{id:52,category:"engineering",title:"Runge Kutta 4th Order",keywords:["runge","kutta"],
simple:"Much better than Euler. Standard in MATLAB.",
how:"Take 4 slopes per step and average them.",
examples:[{q:"RK4 for y prime equals y",a:"Error is very small"},{q:"Step size can be bigger",a:"Than Euler"},{q:"4 function evaluations per step",a:"More work but worth it"},{q:"Used in simulink",a:"Default ODE solver"},{q:"Accuracy fourth order",a:"Error proportional to step to the 4"}],
examTip:"If you need accuracy, use RK4"},

{id:53,category:"engineering",title:"Finite Difference Method",keywords:["finite","difference"],
simple:"Turn derivatives into differences.",
how:"Forward difference. Backward difference. Central difference.",
examples:[{q:"First derivative",a:"f x plus h minus f x divided by h"},{q:"Second derivative",a:"f x plus h minus 2f x plus f x minus h divided by h squared"},{q:"Heat equation",a:"Use time and space differences"},{q:"Boundary conditions",a:"Important"},{q:"Stability condition",a:"Step size must be small"}],
examTip:"Central difference is second order accurate"},

{id:54,category:"engineering",title:"Convolution in Time Domain",keywords:["convolution","signal"],
simple:"Output equals input convolved with impulse response.",
how:"Flip one signal. Slide it. Multiply and add.",
examples:[{q:"Two rectangles",a:"Result is triangle"},{q:"LTI system",a:"Output is convolution"},{q:"In frequency domain",a:"Convolution becomes multiplication"},{q:"Used in filters",a:"FIR filter"},{q:"Commutative",a:"A convolve B equals B convolve A"}],
examTip:"Long division in time equals multiplication in frequency"},

{id:55,category:"engineering",title:"Sampling Theorem Nyquist",keywords:["sampling","nyquist"],
simple:"To capture signal, sample at least twice highest frequency.",
how:"Sampling frequency must be greater than 2 times signal bandwidth.",
examples:[{q:"Audio 20 kHz",a:"Sample at 44.1 kHz"},{q:"Below Nyquist",a:"Aliasing happens"},{q:"Anti aliasing filter",a:"Used before ADC"},{q:"CD quality",a:"44.1 kHz"},{q:"Reconstruct",a:"Use sinc function"}],
examTip:"If you sample 10 kHz signal at 15 kHz, you get aliasing"},

{id:56,category:"engineering",title:"FFT Fast Fourier Transform",keywords:["fft","frequency"],
simple:"Fast way to compute Fourier transform.",
how:"Break signal in half repeatedly. N log N instead of N squared.",
examples:[{q:"1024 point FFT",a:"Very fast"},{q:"Used in spectrum analyzer",a:""},{q:"Radix 2",a:"N must be power of 2"},{q:"Inverse FFT",a:"Same algorithm"},{q:"Zero padding",a:"For better frequency resolution"}],
examTip:"FFT is just fast DFT"},

{id:57,category:"engineering",title:"Error Analysis",keywords:["error","numerical"],
simple:"How wrong is your answer.",
how:"Absolute error. Relative error. Percent error.",
examples:[{q:"True 100, measured 98",a:"Absolute error 2. Percent error 2 percent"},{q:"Round off error",a:"From finite digits"},{q:"Truncation error",a:"From cutting series"},{q:"Condition number",a:"Sensitivity to input error"},{q:"Error propagation",a:"Add in quadrature"}],
examTip:"Always quote answer with error bounds"},

{id:58,category:"engineering",title:"Curve Fitting Least Squares",keywords:["curve","fitting"],
simple:"Find best line through noisy data.",
how:"Minimize sum of squared errors.",
examples:[{q:"Linear fit",a:"y equals mx plus b"},{q:"Polynomial fit",a:"Higher order"},{q:"Exponential fit",a:"Take log first"},{q:"R squared",a:"How good is fit"},{q:"Used in experiments",a:"Lab data"}],
examTip:"Normal equations give m and b"},

{id:59,category:"engineering",title:"Linear Regression",keywords:["regression","statistics"],
simple:"Predict y from x.",
how:"Find line that minimizes squared distance to points.",
examples:[{q:"Sales vs advertising",a:"Find slope"},{q:"Correlation",a:"How related are x and y"},{q:"Multiple regression",a:"More than 1 x"},{q:"Residuals",a:"Difference from line"},{q:"Overfitting",a:"Too many parameters"}],
examTip:"Slope equals covariance divided by variance of x"},

{id:60,category:"engineering",title:"Optimization Gradient Descent",keywords:["optimization","gradient"],
simple:"Find minimum of a function.",
how:"Walk downhill in direction of negative gradient.",
examples:[{q:"Find minimum of x squared",a:"Gradient is 2x. Walk to 0"},{q:"Learning rate",a:"Step size"},{q:"Local minimum",a:"May get stuck"},{q:"Used in machine learning",a:"Train neural networks"},{q:"Momentum",a:"Helps go faster"}],
examTip:"Pick learning rate carefully. Too big you overshoot"}
];
